### ISSUE TITLE
CPU & GPU

### ISSUE THREAD

**Issue by pharringtonp19** [jorenham/jax_pep503#2]
I have access to two machines. One that has a gpu and another that doesn't.

Is it possible to set-up the pyproj.toml file so that the right version of jax is used for each machine?

**Comment by jorenham** [comment]
This is more related to python-poetry, but I have some idea's on how you could do this:

You could try to use environment markers ([docs](https://python-poetry.org/docs/dependency-specification/#using-environment-markers)) in combination with multiple dependencies ([docs](https://python-poetry.org/docs/dependency-specification/#multiple-constraints-dependencies)), 

If that doesn't work in your case, you could try to use extra's instead ([docs](https://python-poetry.org/docs/pyproject/#extras)), so that you install you project on your machines with e.g. `pip install myproject[gpu]` and `pip install myproject[cpu]`.

**Comment by pharringtonp19** [comment]
@jorenham Thanks! I will look into your suggestions and reopen if I have further questions
